// DO NOT edit this file.
// Please work in the pre-post-test html, scss, and component.ts files only.

import { trigger, group, query, animateChild, state, style, animate, transition } from '@angular/animations';

export const PrePostTestAnimations = [
];
